import {
  AreaResponseDTO,
  PandalResponseDTO,
  PandalDetailResponseDTO,
  MetroStationResponseDTO,
  LineResponseDTO,
} from '../types/api';

export const MOCK_AREAS: AreaResponseDTO[] = [
  { id: 1, name: 'South Kolkata' },
  { id: 2, name: 'North Kolkata' },
  { id: 3, name: 'Central Kolkata' },
  { id: 4, name: 'East Kolkata' },
];

export const MOCK_METRO_LINES: LineResponseDTO[] = [
  { name: 'Blue Line' },
  { name: 'Green Line' },
  { name: 'Purple Line' },
  { name: 'Orange Line' },
];

export const MOCK_PANDALS: PandalResponseDTO[] = [
  {
    id: 1,
    name: 'Deshapriyo Park',
    address: 'Deshapriya Park, Rasbehari Avenue, Kolkata',
    description: 'Deshapriya Park Durga Puja is one of the oldest, largest, and most famous mega-budget community festivals in South Kolkata, organized since 1938 by the Ballygunge Sarbojanin Durgotsab Samity.',
    imageUrl: null,
    latitude: 22.5183,
    longitude: 88.3537,
    areaId: 1,
    areaName: 'South Kolkata',
    bestTimeToVisit: 'Evening',
  },
  {
    id: 2,
    name: 'Ekdalia Evergreen',
    address: 'Ekdalia Road, Gariahat / Ballygunge, Kolkata',
    description: 'Ekdalia Evergreen Club Durga Puja is a famous, long-running traditional festival located in Gariahat and Ballygunge, South Kolkata.',
    imageUrl: null,
    latitude: 22.521,
    longitude: 88.366,
    areaId: 1,
    areaName: 'South Kolkata',
    bestTimeToVisit: 'Late Night',
  },
  {
    id: 3,
    name: 'Chetla Agrani',
    address: '14 Peary Mohan Roy Road, Chetla, Kolkata 700027',
    description: 'In South Kolkata hosts one of the city\'s most famous and grand Durga Puja celebrations, renowned for immersive social themes and artistic installations.',
    imageUrl: null,
    latitude: 22.5164,
    longitude: 88.3371,
    areaId: 1,
    areaName: 'South Kolkata',
    bestTimeToVisit: 'Evening',
  },
  {
    id: 4,
    name: 'Tridhara Sammilani',
    address: 'Rasbehari / Ballygunge area, Kolkata',
    description: 'Tridhara Sammilani is one of the most famous and popular community Durga Puja celebrations in South Kolkata, known for its creative themes, grand artistic setups, and social initiatives.',
    imageUrl: null,
    latitude: 22.5196,
    longitude: 88.3554,
    areaId: 1,
    areaName: 'South Kolkata',
    bestTimeToVisit: 'Night',
  },
  {
    id: 5,
    name: 'Ballygunge Cultural',
    address: '57, Jatin Das Road, Lake Terrace, Ballygunge, Kolkata 700029',
    description: 'One of South Kolkata\'s most famous and traditional community (Sarbojanin) Durga Puja celebrations, emphasizing authentic traditional idol forms and classical ambiance.',
    imageUrl: null,
    latitude: 22.519,
    longitude: 88.3638,
    areaId: 1,
    areaName: 'South Kolkata',
    bestTimeToVisit: 'Morning / Afternoon',
  },
  {
    id: 6,
    name: 'Singhi Park',
    address: 'Singhi Park, Gariahat / Ballygunge, Kolkata',
    description: 'Singhi Park Sarbojanin Durgotsav is one of the oldest and most famous community Durga Puja celebrations in South Kolkata, celebrated for traditional lighting and grand temple facades.',
    imageUrl: null,
    latitude: 22.5222,
    longitude: 88.3671,
    areaId: 1,
    areaName: 'South Kolkata',
    bestTimeToVisit: 'Late Evening',
  },
  {
    id: 7,
    name: 'Hindusthan Park',
    address: 'Rajendra Prasad Colony, Tollygunge, Lake Gardens, Kolkata-700045',
    description: 'Celebrated for bold, thought-provoking themes that blend deep cultural roots with modern storytelling and sustainable architecture.',
    imageUrl: null,
    latitude: 22.5173,
    longitude: 88.3615,
    areaId: 1,
    areaName: 'South Kolkata',
    bestTimeToVisit: 'Evening',
  },
  {
    id: 8,
    name: 'Badamtala Ashar Sangha',
    address: 'Badamtala, Kalighat, Kolkata',
    description: 'Badamtala Ashar Sangha is one of the oldest, most famous Durga Puja committees in South Kolkata, located right beside Kalighat Metro.',
    imageUrl: null,
    latitude: 22.5233,
    longitude: 88.3444,
    areaId: 1,
    areaName: 'South Kolkata',
    bestTimeToVisit: 'Evening',
  },
  {
    id: 9,
    name: 'Bosepukur Sitala Mandir',
    address: 'Bosepukur, Kasba, Kolkata',
    description: 'Famous for pioneering the city\'s modern theme-based puja movement with clay cup and indigenous rural handicraft architectures.',
    imageUrl: null,
    latitude: 22.5218,
    longitude: 88.3842,
    areaId: 1,
    areaName: 'South Kolkata',
    bestTimeToVisit: 'Afternoon / Evening',
  },
  {
    id: 10,
    name: 'Naktala Udayan Sangha',
    address: '1/250, Naktala Road, Naktala, Garia, Kolkata 700047',
    description: 'Renowned for its avant-garde artistic concepts, kinetic lighting, and magnificent community celebrations.',
    imageUrl: null,
    latitude: 22.4719,
    longitude: 88.3686,
    areaId: 1,
    areaName: 'South Kolkata',
    bestTimeToVisit: 'Midnight',
  },
  {
    id: 11,
    name: 'Suruchi Sangha',
    address: '500 & 505, Block M, New Alipore',
    description: 'Celebrated for representing Indian state handicrafts and folk traditions with monumental outdoor installations and musical compositions.',
    imageUrl: null,
    latitude: 22.5121,
    longitude: 88.3283,
    areaId: 1,
    areaName: 'South Kolkata',
    bestTimeToVisit: 'Late Night',
  },
  {
    id: 12,
    name: 'Maddox Square',
    address: 'Maddox Square, Hazra, Kolkata',
    description: 'The quintessential open-air hangout (adda) of Kolkata Durga Puja, featuring a majestic traditional Ekchala Pratima under a heritage pandal canopy.',
    imageUrl: null,
    latitude: 22.5292,
    longitude: 88.3567,
    areaId: 1,
    areaName: 'South Kolkata',
    bestTimeToVisit: 'Evening Adda',
  },
  {
    id: 13,
    name: '66 Pally',
    address: '9/5a/1, Nepal Bhattacharya Street, Kalighat, Kolkata 700026',
    description: 'A trailblazing Durga Puja celebration in South Kolkata, renowned for historic female priestess rituals and organic art installations.',
    imageUrl: null,
    latitude: 22.5226,
    longitude: 88.3441,
    areaId: 1,
    areaName: 'South Kolkata',
    bestTimeToVisit: 'Late Evening',
  },
  {
    id: 20,
    name: 'Mudiali Club',
    address: '37, S.R. Das Road, Mudiali, Kalighat, Kolkata 700026',
    description: 'World-renowned for mesmerizing light chandeliers, intricate brass and metal handicrafts, and serene traditional divinity.',
    imageUrl: null,
    latitude: 22.5111,
    longitude: 88.3468,
    areaId: 1,
    areaName: 'South Kolkata',
    bestTimeToVisit: 'Late Night',
  },
  // North Kolkata
  {
    id: 69,
    name: 'Baghbazar Sarbojanin Durgotsav',
    address: '78, Bagbazar St, Baghbazar, Kolkata 700003',
    description: 'One of Bengal\'s oldest community pujas, founded in 1919. Famous for its authentic traditional Ekchala Pratima, historic carnival, and classical Bengali aristocratic atmosphere.',
    imageUrl: null,
    latitude: 22.6022,
    longitude: 88.3628,
    areaId: 2,
    areaName: 'North Kolkata',
    bestTimeToVisit: 'Morning / Afternoon',
  },
  {
    id: 73,
    name: 'Kumartuli Park Sarbojanin Durgotsab',
    address: '8B Abhay Mitra St, Kumartuli, Kolkata 700005',
    description: 'Situated in the heart of Kolkata\'s generational idol-makers\' clay sculpting colony. Renowned for innovative concepts, grandeur, and fine artistry.',
    imageUrl: null,
    latitude: 22.6015,
    longitude: 88.3601,
    areaId: 2,
    areaName: 'North Kolkata',
    bestTimeToVisit: 'Evening',
  },
  {
    id: 71,
    name: 'Hatkhola Gosaipara Sarbojonin Durgotsab',
    address: 'Gossain Para Ln, Kumartuli, Kolkata 700005',
    description: 'A celebrated North Kolkata heritage puja known for authentic rituals and vibrant community involvement near Kumartuli ghat.',
    imageUrl: null,
    latitude: 22.5968,
    longitude: 88.3605,
    areaId: 2,
    areaName: 'North Kolkata',
    bestTimeToVisit: 'Evening',
  },
  {
    id: 76,
    name: 'Nimtala Sarbojanin Durga Puja',
    address: '16B, Nimtala Ln, Ahiritola, Kolkata 700006',
    description: 'Heritage riverside celebration famous for its cultural presence along the historic Ganges ghats.',
    imageUrl: null,
    latitude: 22.5942,
    longitude: 88.3552,
    areaId: 2,
    areaName: 'North Kolkata',
    bestTimeToVisit: 'Late Night',
  },
  {
    id: 89,
    name: 'Jagat Mukherjee Park',
    address: '1 Jatindra Mohan Ave, Sovabazar, Kolkata 700005',
    description: 'Pioneers of creative thematic structures in North Kolkata, renowned for engineering marvels and immersive walk-through pandals.',
    imageUrl: null,
    latitude: 22.6042,
    longitude: 88.3687,
    areaId: 2,
    areaName: 'North Kolkata',
    bestTimeToVisit: 'Evening / Midnight',
  },
  // Central Kolkata
  {
    id: 91,
    name: 'College Square',
    address: '53, College St, College Square, Kolkata 700073',
    description: 'World-famous for its majestic illuminated temple facade reflecting over the heritage lake, attracting millions of visitors every year.',
    imageUrl: null,
    latitude: 22.5744,
    longitude: 88.3639,
    areaId: 3,
    areaName: 'Central Kolkata',
    bestTimeToVisit: 'Evening / Night',
  },
  {
    id: 92,
    name: 'Md. Ali Park',
    address: 'Mahatma Gandhi Rd, Central Kolkata, Kolkata 700073',
    description: 'One of the most famous and visited pandals in Central Kolkata, celebrated for its monumental replicas of world heritage monuments and glittering lights.',
    imageUrl: null,
    latitude: 22.5802,
    longitude: 88.3608,
    areaId: 3,
    areaName: 'Central Kolkata',
    bestTimeToVisit: 'Late Night',
  },
  {
    id: 93,
    name: 'Santosh Mitra Square (Lebutala)',
    address: 'Lebutala, Bowbazar, Kolkata 700012',
    description: 'Renowned for record-breaking grand themes, laser-light extravaganzas, and diamond jubilee celebration architecture.',
    imageUrl: null,
    latitude: 22.5695,
    longitude: 88.3672,
    areaId: 3,
    areaName: 'Central Kolkata',
    bestTimeToVisit: 'Midnight',
  },
];

export const MOCK_METRO_STATIONS: Record<string, MetroStationResponseDTO[]> = {
  'Blue Line': [
    { id: 1, name: 'Dakshineswar', line: 'Blue Line', latitude: 22.653971, longitude: 88.363724 },
    { id: 2, name: 'Baranagar Road', line: 'Blue Line', latitude: 22.653529, longitude: 88.378873 },
    { id: 3, name: 'Noapara', line: 'Blue Line', latitude: 22.639673, longitude: 88.393978 },
    { id: 4, name: 'Dum Dum', line: 'Blue Line', latitude: 22.621027, longitude: 88.392818 },
    { id: 5, name: 'Belgachia', line: 'Blue Line', latitude: 22.60592, longitude: 88.38639 },
    { id: 6, name: 'Shyambazar', line: 'Blue Line', latitude: 22.601313, longitude: 88.372586 },
    { id: 7, name: 'Sovabazar Sutanuti', line: 'Blue Line', latitude: 22.596029, longitude: 88.365285 },
    { id: 8, name: 'Girish Park', line: 'Blue Line', latitude: 22.587143, longitude: 88.363083 },
    { id: 9, name: 'Mahatma Gandhi Road', line: 'Blue Line', latitude: 22.580858, longitude: 88.361401 },
    { id: 10, name: 'Central', line: 'Blue Line', latitude: 22.57247, longitude: 88.358788 },
    { id: 11, name: 'Chandni Chowk', line: 'Blue Line', latitude: 22.566796, longitude: 88.354137 },
    { id: 12, name: 'Esplanade', line: 'Blue Line, Green Line', latitude: 22.564444, longitude: 88.351667 },
    { id: 13, name: 'Park Street', line: 'Blue Line', latitude: 22.555, longitude: 88.350278 },
    { id: 14, name: 'Maidan', line: 'Blue Line', latitude: 22.549444, longitude: 88.348889 },
    { id: 15, name: 'Rabindra Sadan', line: 'Blue Line', latitude: 22.541389, longitude: 88.347222 },
    { id: 16, name: 'Netaji Bhavan', line: 'Blue Line', latitude: 22.533333, longitude: 88.346111 },
    { id: 17, name: 'Jatin Das Park', line: 'Blue Line', latitude: 22.524262, longitude: 88.346489 },
    { id: 18, name: 'Kalighat', line: 'Blue Line', latitude: 22.516652, longitude: 88.346003 },
    { id: 19, name: 'Rabindra Sarobar', line: 'Blue Line', latitude: 22.507222, longitude: 88.345556 },
    { id: 20, name: 'Mahanayak Uttam Kumar', line: 'Blue Line', latitude: 22.494722, longitude: 88.345 },
    { id: 21, name: 'Netaji', line: 'Blue Line', latitude: 22.480976, longitude: 88.346 },
    { id: 22, name: 'Masterda Surya Sen', line: 'Blue Line', latitude: 22.473521, longitude: 88.360871 },
    { id: 23, name: 'Gitanjali', line: 'Blue Line', latitude: 22.47, longitude: 88.37 },
    { id: 24, name: 'Kavi Nazrul', line: 'Blue Line', latitude: 22.464167, longitude: 88.380556 },
    { id: 25, name: 'Sahid Khudiram', line: 'Blue Line', latitude: 22.465972, longitude: 88.391667 },
    { id: 26, name: 'Kavi Subhash', line: 'Blue Line, Orange Line', latitude: 22.471944, longitude: 88.398056 },
  ],
  'Green Line': [
    { id: 27, name: 'Howrah Maidan', line: 'Green Line', latitude: 22.585, longitude: 88.326 },
    { id: 28, name: 'Howrah', line: 'Green Line', latitude: 22.584, longitude: 88.343 },
    { id: 29, name: 'Mahakaran', line: 'Green Line', latitude: 22.571, longitude: 88.348 },
    { id: 30, name: 'Esplanade', line: 'Blue Line, Green Line', latitude: 22.564444, longitude: 88.351667 },
    { id: 31, name: 'Sealdah', line: 'Green Line', latitude: 22.567, longitude: 88.371 },
    { id: 32, name: 'Phoolbagan', line: 'Green Line', latitude: 22.572, longitude: 88.391 },
    { id: 33, name: 'Salt Lake Stadium', line: 'Green Line', latitude: 22.571, longitude: 88.404 },
    { id: 34, name: 'Bengal Chemical', line: 'Green Line', latitude: 22.574, longitude: 88.411 },
    { id: 35, name: 'City Centre', line: 'Green Line', latitude: 22.583, longitude: 88.408 },
    { id: 36, name: 'Central Park', line: 'Green Line', latitude: 22.588, longitude: 88.415 },
    { id: 37, name: 'Karunamoyee', line: 'Green Line', latitude: 22.587, longitude: 88.423 },
    { id: 38, name: 'Salt Lake Sector V', line: 'Green Line', latitude: 22.581, longitude: 88.431 },
  ],
  'Purple Line': [
    { id: 39, name: 'Joka', line: 'Purple Line', latitude: 22.451, longitude: 88.303 },
    { id: 40, name: 'Thakurpukur', line: 'Purple Line', latitude: 22.463, longitude: 88.307 },
    { id: 41, name: 'Sakherbazar', line: 'Purple Line', latitude: 22.474, longitude: 88.312 },
    { id: 42, name: 'Behala Chowrasta', line: 'Purple Line', latitude: 22.484, longitude: 88.316 },
    { id: 43, name: 'Behala Bazar', line: 'Purple Line', latitude: 22.496, longitude: 88.321 },
    { id: 44, name: 'Taratala', line: 'Purple Line', latitude: 22.508, longitude: 88.324 },
    { id: 45, name: 'Majerhat', line: 'Purple Line', latitude: 22.519, longitude: 88.326 },
  ],
  'Orange Line': [
    { id: 46, name: 'Kavi Subhash', line: 'Blue Line, Orange Line', latitude: 22.471944, longitude: 88.398056 },
    { id: 47, name: 'Satyajit Ray', line: 'Orange Line', latitude: 22.482, longitude: 88.399 },
    { id: 48, name: 'Jyotirindra Nandy', line: 'Orange Line', latitude: 22.491, longitude: 88.401 },
    { id: 49, name: 'Kavi Sukanta', line: 'Orange Line', latitude: 22.502, longitude: 88.402 },
    { id: 50, name: 'Hemanta Mukhopadhyay', line: 'Orange Line', latitude: 22.513, longitude: 88.403 },
  ],
};

export function getMockPandalDetail(pandalId: number): PandalDetailResponseDTO {
  const pandal = MOCK_PANDALS.find((p) => p.id === pandalId) || MOCK_PANDALS[0];
  const kalighatStation: MetroStationResponseDTO = {
    id: 18,
    name: 'Kalighat',
    line: 'Blue Line',
    latitude: 22.516652,
    longitude: 88.346003,
    distanceKm: 0.8,
    walkingTimeMinutes: 10,
  };
  const jatinDasStation: MetroStationResponseDTO = {
    id: 17,
    name: 'Jatin Das Park',
    line: 'Blue Line',
    latitude: 22.524262,
    longitude: 88.346489,
    distanceKm: 0.9,
    walkingTimeMinutes: 11,
  };
  const rabindraSarobarStation: MetroStationResponseDTO = {
    id: 19,
    name: 'Rabindra Sarobar',
    line: 'Blue Line',
    latitude: 22.507222,
    longitude: 88.345556,
    distanceKm: 1.4,
    walkingTimeMinutes: 16,
  };

  return {
    id: pandal.id,
    name: pandal.name,
    address: pandal.address,
    description: pandal.description,
    imageUrl: pandal.imageUrl,
    latitude: pandal.latitude,
    longitude: pandal.longitude,
    bestTimeToVisit: pandal.bestTimeToVisit || 'Evening',
    areaName: pandal.areaName,
    nearbyMetros: [kalighatStation, jatinDasStation, rabindraSarobarStation],
  };
}

